[profile.default]
src = 'contracts'
out = 'out'
test = 'test'
remappings = [
    "forge-std/=lib/forge-std/src/"
]
libs = [
    'lib'
]

# Compiler settings
via_ir = true  # Enable IR-based code generation
optimizer = true  # Enable the optimizer
optimizer_runs = 200  # Number of optimizer runs

ffi=true
verbosity=5

# Mainnet forking configuration
[rpc_endpoints]
optimism = "https://mainnet.optimism.io"
lisk = "https://rpc.api.lisk.com"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config